set(GLADE_FILE ${CMAKE_ARGV3})
set(RESULT_HEADER ${CMAKE_ARGV4})
set(TAB_NAME ${CMAKE_ARGV5})
set(HEADER_IN ${CMAKE_ARGV6})

file(READ ${GLADE_FILE} TAB_SOURCE)
string(REGEX REPLACE "\n *" "" TAB_SOURCE ${TAB_SOURCE})

configure_file(${HEADER_IN} ${RESULT_HEADER} ESCAPE_QUOTES)
